#!/usr/bin/env bash
# Use ping to check connection to a specific IP
if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-90{1,3}$ ]]
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_of_the_network {IP_ADDRESS}"
fi
