#!/usr/bin/env bash

# Backup /etc/hosts file
cp /etc/hosts /etc/hosts.bak

# Update /etc/hosts file
sed -i '/^127\.0\.0\.1[[:space:]]localhost$/s/127\.0\.0\.1/127.0.0.2/' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

echo "Changes applied:"
echo "localhost resolves to 127.0.0.2"
echo "facebook.com resolves to 8.8.8.8"

